### ISSUE TITLE
Cannot download dataset.

### ISSUE THREAD

**Issue by SangbaekYoo** [eigenvivek/DiffDRR-Datasets#11]
Hello. Thank you for sharing good open-source. I'm trying to run codes related to DiffDRR, but I got stuck at the stage of downloading the dataset. Could you please help me with this issue? 

I think that the download is currently blocked. Could you please help me understand what the issue might be?

I installed diffdrrdata and just tried to run below code.
```
from diffdrrdata.ljubljana import LjubljanaDataset, Transforms

# Load a subject from the LjubljanaDataset
ljubljana = LjubljanaDataset(id_number=1)
gt, pose, focal_len, height, width, delx, dely, x0, y0 = ljubljana[0]

# Initialize the DRR module
subsample = 8
drr = DRR(
    ljubljana.subject,
    focal_len,
    height // subsample,
    delx * subsample,
    width // subsample,
    dely * subsample,
    x0=-x0,
    y0=y0,
    reverse_x_axis=False,
)
transform = Transforms(height // subsample, width // subsample)

# Render a DRR from the ground truth camera pose
img = drr(pose)
gt, img = transform(gt), transform(img)
plot_drr(torch.concat([gt, img]), title=["Downsampled X-ray", "DRR"])
plt.show()
```

**Comment by eigenvivek** [comment]
Are you using the dev version on GitHub? @momen-mh noticed an issue with the download command for the Ljubljana dataset in the latest PyPI version. His PR should fix that: https://github.com/eigenvivek/DiffDRR-Datasets/commit/f000ef59f94983d7c6b5fbd8df459fa1c75543d4

**Comment by eigenvivek** [comment]
Hi @SangbaekYoo , just uploaded a new version of the package to pypi with @momen-mh's fix.
